services:
  mercurial-mcp:
    build: .
    volumes:
      # Mount system configurations (read-only)
      - ${HGRC_PATH}:/root/.hgrc:ro
      - ${ARCRC_PATH}:/root/.arcrc:ro
      
      # Mount the Target Repositories
      # This path is where we will execute hg/arc commands
      - ${AUCTION_PROJECT_PATH}:/app/repo
      
      # Mount Arcanist
      - ${ARCANIST_PROJECT_PATH}:/app/arcanist

    env_file:
      - .env
